// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2GtDKrFS71IA1mF7D_sda2FCPo55WbA',
    appId: '1:75328533612:web:e0c841695d73696a455449',
    messagingSenderId: '75328533612',
    projectId: 'service-nest-75a76',
    authDomain: 'service-nest-75a76.firebaseapp.com',
    storageBucket: 'service-nest-75a76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsPTCSwNhYXtULXxesamGmg9QIfDJX6sA',
    appId: '1:75328533612:android:87eee82c3e4ee807455449',
    messagingSenderId: '75328533612',
    projectId: 'service-nest-75a76',
    storageBucket: 'service-nest-75a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDuvKG0Cr_KR6NU12cMCgEY3IJnFxYOXM',
    appId: '1:75328533612:ios:d6a327c3c97ceab3455449',
    messagingSenderId: '75328533612',
    projectId: 'service-nest-75a76',
    storageBucket: 'service-nest-75a76.appspot.com',
    iosBundleId: 'com.example.servicenest.serviceNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDuvKG0Cr_KR6NU12cMCgEY3IJnFxYOXM',
    appId: '1:75328533612:ios:d6a327c3c97ceab3455449',
    messagingSenderId: '75328533612',
    projectId: 'service-nest-75a76',
    storageBucket: 'service-nest-75a76.appspot.com',
    iosBundleId: 'com.example.servicenest.serviceNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2GtDKrFS71IA1mF7D_sda2FCPo55WbA',
    appId: '1:75328533612:web:e8d53b8f7b5a0793455449',
    messagingSenderId: '75328533612',
    projectId: 'service-nest-75a76',
    authDomain: 'service-nest-75a76.firebaseapp.com',
    storageBucket: 'service-nest-75a76.appspot.com',
  );
}
